# Generated by Django 5.1.4 on 2025-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCODE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_code'),
        ),
    ]
